name: Publish stories if changed

on:
  push:
    branches:
      - master
    paths: ['stories/**']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build Storybook
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          buildScriptName: build-storybook
          storybookBuildDir: storybook-static
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: storybook-static
          FOLDER: storybook-static
